### PR TITLE
Add a Dockerfile and beautify README.md

### PR DESCRIPTION
**Pull request by netanelravid**
1. I added a Dockerfile in order to create a isolated environment for EyeWitness.
2. I edited the README.md:
    - I've Beautify it in order to be more convenient to read
    - I've add a Docker section

P.S. Its my first pull request ever :)

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Awesome, thank you very much for taking the time to submit this!  I will be reviewing this shortly, as I am currently traveling.  Look forward to getting this merged in!

**Comment by netanelravid** [comment]
Great! looking forward for review.
Enjoy your trip and be safe!

**Comment by ChrisTruncer** [comment]
All looks great to me, getting this merged in now.  Thanks for the submission!

**Comment by netanelravid** [comment]
Anytime :)

**Pull request merged**
