### PR TITLE
Fix url startswith matching

### PR DESCRIPTION
**Pull request by rpunnett**
Noticed that if I had uppercase HTTP(S) the script would still try to add HTTP(S) to the URLS, breaking the requests. The fault was in the "startswith" method being case sensitive. Compiled regex is fast, so I created a regex class with easy methods ("isHTTP", "isVNC", "isRDP") to check if the service matches. This is case insensitive and so will match even if "HtTpS://" is passed. 

In addition I made the following small changes:

- Modified the variable "line" to "url_line" for extra clarity
- Added a ".lower()" method to the initial strip on "url_line" ("line") so it will display clean in the CLI. Otherwise if for whatever reason they did pass "HtTpS://", it looks dirty when presented in CLI.

### CODE REVIEW

**Comment by paalbra** [comment]
You shouldn't convert the URLs to lower case. A webpath might be case sensitive.

Also:

Urlparse is already a dependency. The fix should rather be implemented by benefiting from urlparse.

```
>>> from urlparse import urlparse
>>> urlparse("HTtp://example.com/SomePage.html")
ParseResult(scheme='http', netloc='example.com', path='/SomePage.html', params='', query='', fragment='')
>>> urlparse("http://example.com/SomePage.html")
ParseResult(scheme='http', netloc='example.com', path='/SomePage.html', params='', query='', fragment='')
>>> urlparse("rdp://example.com:3389")
ParseResult(scheme='rdp', netloc='example.com:3389', path='', params='', query='', fragment='')
```

**Comment by ChrisTruncer** [comment]
Thanks for the review @paalbra. @rpunnett - you have any thoughts on the suggestion?

**Comment by rpunnett** [comment]
Good points. I did some speed tests for urlparse vs the compiled regex and for 1 million entries, urlparse was a good second faster. Also simplifies the code and keeps it more pythonic.

Though I prefer the display of lowercase, I can see where it would effect the path. Individuals may also want to see the unmodified URL.

Let me rework it to keep it simple.

**Comment by paalbra** [comment]
I haven't tried to actually run this code, but it looks cleaner now.

But: The now unused regex.py is still there. It should be removed.

**Comment by rpunnett** [comment]
See Paal, this is why you get paid the big bucks.

**Comment by ChrisTruncer** [comment]
This looks to still be appending the http or https to it.

stillappending

**Comment by ChrisTruncer** [comment]
Any additional fixes?

**Comment by rpunnett** [comment]
Yeah, I will fix it over the holiday weekend. Do a new pull and add what we
discussed. Been slammed.

**Comment by rpunnett** [comment]
Kind of late, but it's fixed now. Spent a little bit on it as it still does append http:// later on in the code. As the matching now works, just left the later pending of HTTP alone. 

Ran test as below:

https://www.github.com
HTTPS://www.github.com
hTTps://www.github.com
HTTp://purple.com
httP://purple.com
wWw.purple.cOm
aol.coM
rDp://98.114.182.186
rDP://98.114.182.186
98.114.182.186

image

**Comment by ChrisTruncer** [comment]
Looks good to me, thanks for getting this sent over. Merged

**Pull request merged**
