### PR TITLE
Nessus parse: Differentiate between http and https when parsing servi…

### PR DESCRIPTION
**Pull request by jojoob**
When using a nesses scan as input for EyeWittness HTTPS servers running on a non default port are not detected correctly. Instead they are treated as HTTP servers.
This happens due to nessus' service detection plugin uses www as the svc_name for HTTP and HTTPS. Only the plugin output offers a hint if the web server is HTTP or HTTPS.

The patch fixes the problem by differentiate the services on basis of the plugin_output of the service detection plugin.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Great catch and nice job writing the push for this. I looked it over with a recent scan I did and looks like this should work great. Merging, thanks for submitting!

**Comment by ChrisTruncer** [comment]
I might have wanted to test this first, my fault. I am running into an issue where EyeWitness is now parsing servers on 443 as HTTP. Are you running into this too?

**Comment by ChrisTruncer** [comment]
This should be fixed now (ideally), I just swapped around the order of the if statement to make your addition be second, and have the known HTTPS ports check go first.

**Comment by jojoob** [comment]
Maybe this is caused by different versions of nessus? Sounds like the plugin_output isn't reliable.

**Comment by jojoob** [comment]
My nessus version is 6.11.3 And I tested with the appended file.

[nessus-test.txt](https://github.com/ChrisTruncer/EyeWitness/files/1645603/nessus-test.txt) (.nessus isn't supported by github)

**Pull request merged**
