### PR TITLE
Fix various issues emitted by the pylint linter

### LINKED ISSUE #282: Lint pass over python code
Using a linter like https://www.pylint.org/ emits a list of issues in the python code.

Some of the issues are hurting readability and maintainability, and should be resolved.

I would suggest doing a full lint pass over the code base.

### PR DESCRIPTION
**Pull request by paalbra**
This is intended to fix #282 even though the issue got closed.

I've tried not to touch/move actual logic unless it obviously made sense to do so.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hey, thanks for sending this. Right now I have a couple pull requests I am waiting on prior to merging this, and it looks like there are some conflicts. So once the other pull requests are updated, or closed, I think this can be reviewed.

**Comment by paalbra** [comment]
I'll try to resolve the conflicts as they appear.

**Comment by paalbra** [comment]
There were a few major changes in surrounding code, but the conflicts are resolved for now.

**Comment by ChrisTruncer** [comment]
THanks for submitting this again. This will be a big help. I am unfortunately thinking I need to change some of the reporting back to the original format. The usability currently does not seem to be in the best shape, and it might be worth changing back. Just wanted to give a heads up in case once it reverts it breaks (you might be able to revert back to your original PR)

**Comment by ChrisTruncer** [comment]
Sorry paul, the revert back to the old report caused conflicts with this again.

**Comment by paalbra** [comment]
It's a bit hard to keep this pull-request conflict free when master is updated as it touches a lot of files. With the newest changes to master I'm not sure if it makes sense to continue updating the pull-request (it might be best to just abandon this pull-request and do a new pass over master).

Is code consistency/linting considered an issue in this project?

If it's not I guess it won't make sense for me to spend time on a new pull-request?

**Comment by ChrisTruncer** [comment]
At the moment, I wouldn't say linting is my top priority. I'm trying to slowly work through all issues/feature requests. Granted, I try to make it ideally somewhat pep compliant, however I realize there are areas that aren't.

The biggest help to me would be adding in any sort of feature request (like SSL cert parsing, etc.) or any other fix needed. I try to get to each one as I can, however I have been busy as of late which has slowed this down some.

**Comment by paalbra** [comment]
Maybe the best solution is to add some contribution guidelines and config for a linter. Then the project will hopefully converge to being pep compliant/linted in some time.

Is this a better solution?

**Comment by ChrisTruncer** [comment]
TBH, I should really accept any reasonable pull request. While I would prefer a focus on adding in an existing request, making code compliant with pep is absolutely a good contribution and something that would make the codebase easier to maintain.

**Comment by ChrisTruncer** [comment]
closing this for now since it seems this won't be updated. Please feel free to re-submit if you do update it.

**Pull request closed without merging**
