### PR TITLE
Added first version of OCR

### PR DESCRIPTION
**Pull request by Thanathan-k**
I added a very basic idea of using OCR to determine the usernames within a RDP screenshot.

For this to work Tesseract-OCR must be installed (Best working version is 4.0)
Compiling manual is found at https://github.com/tesseract-ocr/tesseract/wiki/Compiling

Also pytesseract 0.1.6 (pip install pytesseract) is needed for this to work.

The basic idea is to check the pixel at (10, width-10) and compare the colorvalue to a list I've added (which right now only consists of my testsystems and might need further testing/adding of more values) to determine which operating system is running and how to crop the image to only display the username for the OCR to read.
The function adds three files in the report depository. domains.txt tries to contain all domains found, users.txt contains usernames with their respective domains and os.txt contains the found operating systems or a message containing the colorvalue of the pixel at (10,width-10) to add this system to the list.

### CODE REVIEW

**Comment by Thanathan-k** [comment]
Just corrected a mistake I made in single parsing and added argument parsing for OCR

**Comment by ChrisTruncer** [comment]
Hey, thanks for sending this over. I'm currently traveling, but once I am home I will certainly look into this!

**Comment by ChrisTruncer** [comment]
Hey, so I'm getting a chance to look at this code now, thanks again for sending it over! I am receiving an error when trying to run this:

Traceback (most recent call last):
  File "./EyeWitness.py", line 611, in <module>
    single_vnc_rdp(cli_parsed, 'rdp')
  File "./EyeWitness.py", line 407, in single_vnc_rdp
    rdp_module.parse_screenshot(obj.screenshot_path, cli_parsed.d)
  File "/tmp/EyeWitness/modules/rdp_module.py", line 214, in parse_screenshot
    img = Image.open(rdp_object.screenshot_path)
AttributeError: 'str' object has no attribute 'screenshot_path'

It looks like you're passing in an attribute, vs. the object itself from my side.

**Comment by Thanathan-k** [comment]
@ChrisTruncer the bug should be fixed now.

**Comment by ChrisTruncer** [comment]
First, I apologize that this has taken me so long to look at and review. I have looked it over, installed the dependencies, and it works. There's some minor things, but I believe this is tesseract misreading the image, programatically it seems to be working great. Only question I have is do you have any interested in including an update to the setup script to install the required dependencies? You could likely do the pip install for the python library and apt-get install for the tesseract package itself. Main reason I'm asking is just to help give full credit to you associated with this pull request.

After I hear back from you and potentially with updates, we'll get this merged in.

Thanks again, and I think this will be an awesome addition.

**Comment by Thanathan-k** [comment]
Don't worry. Glad to hear from you and that you like it.

I'm currently abroad and don't have access to my project. So if you could add the dependencies to the setup script and mention my contribution somewhere I would be okay with it.

**Comment by ChrisTruncer** [comment]
Merged in! Thanks again for the submission!

**Pull request merged**
