### PR TITLE
modified:   login_module.py

### PR DESCRIPTION
**Pull request by Den1al**
Added the "html.parser" option to the BeautifulSoup call to suppress that annoying message popping out every other request.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Thanks for sending this over. @chango77747 can you check this out for your code?

**Comment by ChrisTruncer** [comment]
@chango77747 - ever get the chance to look at this?

**Comment by paalbra** [comment]
I believe this is one of the simplest commands you can run to provoke the message:
```./EyeWitness.py --single https://example.com --headless --active-scan```

```
################################################################################
#                                  EyeWitness                                  #
################################################################################

Attempting to screenshot https://example.com
Attempting active scan against https://example.com
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 597 of the file ./EyeWitness.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "html.parser")

  markup_type=markup_type))

[*] Done! Report written in the /home/myuser/EyeWitness/09292017_143720 folder!
Would you like to open the report now? [Y/n]
```

**Comment by ChrisTruncer** [comment]
Yup, this works perfect. Thanks for sending the pull request, and thanks for the info debugging it @paalbra

**Comment by ChrisTruncer** [comment]
merged

**Pull request merged**
